### PR TITLE
v2.7.3

### PR DESCRIPTION
**Pull request by kra-mo**

### CODE REVIEW

**Comment by kra-mo** [comment]
bot, build

**Comment by bbhtt** [comment]
You're using project group GNOME https://github.com/kra-mo/cartridges/blob/c86f14c4f5039a236990476fd240d0801b29c836/data/hu.kramo.Cartridges.metainfo.xml.in#L22 but your appid does not start with `org.gnome`

That's causing the error. You can add that as a keyword.

**Comment by kra-mo** [comment]
Wait, really? That got approved the last time, I thought that was enough.

*sigh*

**Comment by kra-mo** [comment]
bot, build

**Pull request merged**
